<!-- Animations generated by Loading.io -->
<template lang="html">
	<svg aria-hidden="true" class="visually-hidden" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
		<defs>
			<symbol id="anim-loading" viewBox="0 0 100 100">
				<circle cy="50" cx="38.017" fill="#47b784" r="20">
					<animate attributeName="cx" calcMode="linear" values="30;70;30" keyTimes="0;0.5;1" dur="1" begin="-0.5s" repeatCount="indefinite" />
				</circle>
				<circle cy="50" cx="61.983" fill="#36495d" r="20">
					<animate attributeName="cx" calcMode="linear" values="30;70;30" keyTimes="0;0.5;1" dur="1" begin="0s" repeatCount="indefinite" />
				</circle>
				<circle cy="50" cx="38.017" fill="#47b784" r="20">
					<animate attributeName="cx" calcMode="linear" values="30;70;30" keyTimes="0;0.5;1" dur="1" begin="-0.5s" repeatCount="indefinite" />
					<animate attributeName="fill-opacity" values="0;0;1;1" calcMode="discrete" keyTimes="0;0.499;0.5;1" repeatCount="indefinite" dur="1s" />
				</circle>
			</symbol>
		</defs>
	</svg>
</template>
